### ISSUE TITLE
Additional Guidance for data publishers

### ISSUE THREAD

**Issue by 6a6d74** [wmo-im/wis2-guide#117]
Three things that might be useful guidance for data publishers are pending additions to the WIS2 specs:

1. Coarser resource publication links [WNM issue#41](https://github.com/wmo-im/wis2-notification-message/issues/41)
2. Including links from discovery metadata to external provenance materials [WCMP2 issue#161](https://github.com/wmo-im/wcmp2/issues/161)
3. Referencing WIGOS stations and networks from discovery metadata [WCMP2 issue#19](https://github.com/wmo-im/wcmp2/issues/19)

These are currently marked as "TODO" at the top of the Data Publisher section. Likely these sections won't get added before INFCOM3, so this issue is a prompt to add them later.

**Comment by 6a6d74** [comment]
Have removed the "reminder" in the Guide itself: 

```
 (TODO - MAYBE; add Guidance on "coarser resource publication with interactive links" - see WNM issue #41)

 (TODO - MAYBE; add Guidance on linking to external provenance objects - see WCMP2 issue #161)

 (TODO - MAYBE; add Guidance on referencing WIGOS stations and observing networks - see WCMP2 issue #19)
```

**Comment by 6a6d74** [comment]
Creating task list for future release:

- [ ] Add Guidance on "coarser resource publication with interactive links" - see WNM issue #41)
- [ ] Add Guidance on linking to external provenance objects - see WCMP2 issue #161)
- [ ] Add Guidance on referencing WIGOS stations and observing networks - see WCMP2 issue #19)

**Comment by 6a6d74** [comment]
@tomkralidis - are these three things good candidates for the Cookbook?

**Comment by tomkralidis** [comment]
@6a6d74 I think so.  Objections if I "transfer" this issue to the WIS2 Cookbook?
